#spring:
    #application:
    #    name: cruncher
    #datasource:
    #    driverClassName: com.mysql.jdbc.Driver
    #    url: jdbc:mysql://localhost/test
server:
    port: 9000
token : 
    secret : 9SyECk96oDsTmXfogIieDI0cD/8FpnojlYSUJT5U9I/FGVmBz5oskmjOR8cbXTvoPjX+Pq/T/b1PqpHX0lYm0oCBjXWICA==